version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
        - '8088:8080'
        - '50000:50000'
    container_name: jenkins-casabella
    volumes:
        - ~/jenkins:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock